delimiter |

	CREATE EVENT EVT_STATUS_PROMOTION
		ON SCHEDULE
			EVERY 1 MINUTE
		
        DO BEGIN
		
        DECLARE ID_PROMOTION INT;
		
        DECLARE vPROMOTION CURSOR FOR 
			(SELECT ID FROM PROMOTIONS WHERE DT_END < NOW());
		
        OPEN vPROMOTION;
        
			LOOP
				FETCH vPROMOTION INTO ID_PROMOTION;
                
                UPDATE PROMOTIONS SET STATUS = LOWER('INATIVO') WHERE ID = ID_PROMOTION;
			END LOOP;
		
        CLOSE vPROMOTION;
		END;
